### ISSUE TITLE
App crashing immediately on start

### ISSUE THREAD

**Issue by MarcoFalken588** [zhuanghongji/react-native-openai-translator#1]
After installing the app, i tried to lunch it, and the app is crashing and not open at all

**Comment by zhuanghongji** [comment]
> After installing the app, i tried to lunch it, and the app is crashing and not open at all

@MarcoFalken588 Have you downloaded the apk from the [v0.02](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.2) page? I tested it on my Android device and it works fine.

Can you please provide information about your device, including its platform, system version, brand, and any other relevant details?

It would be appreciated if you could provide a crash record video to help me understand what may happen during the crash.

**Comment by MarcoFalken588** [comment]
> > After installing the app, i tried to lunch it, and the app is crashing and not open at all
> 
> @MarcoFalken588 Have you downloaded the apk from the [v0.02](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.2) page? I tested it on my Android device and it works fine.
> 
> Can you please provide information about your device, including its platform, system version, brand, and any other relevant details?
> 
> It would be appreciated if you could provide a crash record video to help me understand what may happen during the crash.

I sent you an email containing all the information.

**Comment by zhuanghongji** [comment]
> > > After installing the app, i tried to lunch it, and the app is crashing and not open at all
> > 
> > 
> > @MarcoFalken588 Have you downloaded the apk from the [v0.02](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.2) page? I tested it on my Android device and it works fine.
> > Can you please provide information about your device, including its platform, system version, brand, and any other relevant details?
> > It would be appreciated if you could provide a crash record video to help me understand what may happen during the crash.
> 
> I sent you an email containing all the information.

@MarcoFalken588 Thank you for the information you provided. The app may have crashed because version v0.0.2 only supports CPU architecture of arm64-v8a, while your device is armeabi-v7a.

I have now released version [v0.0.3](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.3) which includes an apk version for armeabi-v7a devices. Please try it out and let me know if the crash issue has been resolved.

**Comment by MarcoFalken588** [comment]
> > > > After installing the app, i tried to lunch it, and the app is crashing and not open at all
> > > 
> > > 
> > > @MarcoFalken588 Have you downloaded the apk from the [v0.02](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.2) page? I tested it on my Android device and it works fine.
> > > Can you please provide information about your device, including its platform, system version, brand, and any other relevant details?
> > > It would be appreciated if you could provide a crash record video to help me understand what may happen during the crash.
> > 
> > 
> > I sent you an email containing all the information.
> 
> @MarcoFalken588 Thank you for the information you provided. The app may have crashed because version v0.0.2 only supports CPU architecture of arm64-v8a, while your device is armeabi-v7a.
> 
> I have now released version [v0.0.3](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.3) which includes an apk version for armeabi-v7a devices. Please try it out and let me know if the crash issue has been resolved.

That has resolved the problem.
