### ISSUE TITLE
Typing Orientation Changes When Language is Changed in Different Modes

### ISSUE THREAD

**Issue by MarcoFalken588** [zhuanghongji/react-native-openai-translator#2]
i noice that when i changed the language in any mode : translation mode , polishing mode , summarize mode, analyze mode, bubble mode , the typing orientation changed from Left to Right to Right to Left , to fix that i have to close the app every time and Open it. this problem aperas only when i type something first and then i change the language second, if i change the language before i type anything nothing happened. i noticed that problem in both types of CPU architecture  arm64-v8a, and armeabi-v7a. the two version of the app have that problem 
I sent you an email with a video that shows the problem. I hope you can fix it.

**Comment by zhuanghongji** [comment]
@MarcoFalken588 Hi, thank you for your video. I have already published [v0.0.4](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.4) on GitHub to fix the bug that you mentioned earlier. Please try it out and let me know if it is working.

**Comment by MarcoFalken588** [comment]
> @MarcoFalken588 Hi, thank you for your video. I have already published [v0.0.4](https://github.com/zhuanghongji/react-native-openai-translator/releases/tag/v0.0.4) on GitHub to fix the bug that you mentioned earlier. Please try it out and let me know if it is working.

thank you the the app work great
